{
 "title": "Weekly Crowd_level",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Auslastung", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Auslastung",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawQuery": "SELECT measure_value::double as \"München Süd\" FROM $__database.$__table\n  WHERE time between ago(5m) and now()\n  and location = 'muenchen-sued'\n  LIMIT 1"
    },
    {
     "rawQuery": "SELECT measure_value::double as \"München West\" FROM $__database.$__table\n  WHERE time between ago(5m) and now()\n  and location = 'muenchen-west'\n  LIMIT 1"
    },
    {
     "rawQuery": "SELECT measure_value::double as \"München Ost\" FROM $__database.$__table\n  WHERE time between ago(5m) and now()\n  and location = 'muenchen-ost'\n  LIMIT 1"
    },
    {
     "rawQuery": "SELECT measure_value::double as \"München Einstein\" FROM $__database.$__table\n  WHERE time between ago(5m) and now()\n  and location = 'muenchen-einstein'\n  LIMIT 1"
    }
   ]
  },
  {
   "title": "München West - Hourly heatmap",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "rawQuery": "SELECT \n  BIN(time,15m) AS time,\n  measure_value::double as crowd_lvl\nFROM $__database.$__table\n  WHERE $__timeFilter\n  and measure_name = '$__measure'\n  and location = 'muenchen-west'\ngroup by BIN(time,15m), measure_value::double\n"
    }
   ]
  },
  {
   "title": "München Süd - Hourly heatmap",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 16, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "rawQuery": "SELECT \n  BIN(time,15m) AS time,\n  measure_value::double as crowd_lvl\nFROM $__database.$__table\n  WHERE $__timeFilter\n  and measure_name = '$__measure'\n  and location = 'muenchen-sued'\ngroup by BIN(time,15m), measure_value::double\n"
    }
   ]
  },
  {
   "title": "München Einstein - Hourly heatmap",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 16, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "rawQuery": "SELECT \n  BIN(time,15m) AS time,\n  measure_value::double as crowd_lvl\nFROM $__database.$__table\n  WHERE $__timeFilter\n  and measure_name = '$__measure'\n  and location = 'muenchen-einstein'\ngroup by BIN(time,15m), measure_value::double\n"
    }
   ]
  },
  {
   "title": "München Ost - Hourly heatmap",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "rawQuery": "SELECT \n  BIN(time,15m) AS time,\n  measure_value::double as crowd_lvl\nFROM $__database.$__table\n  WHERE $__timeFilter\n  and measure_name = '$__measure'\n  and location = 'muenchen-ost'\ngroup by BIN(time,15m), measure_value::double\n"
    }
   ]
  },
  {
   "title": "Crowd-level of the last 7 days",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "rawQuery": "SELECT \n  bin(time, 1h) as binned_timestamp,\n  avg(measure_value::double) as crowd_lvl\nFROM $__database.$__table\n  WHERE $__timeFilter\n  and measure_name = '$__measure'\n  and location = 'muenchen-sued'\ngroup by bin(time, 1h)\norder by binned_timestamp asc\n"
    },
    {
     "rawQuery": "SELECT \n  bin(time, 1h) as binned_timestamp,\n  avg(measure_value::double) as crowd_lvl\nFROM $__database.$__table\n  WHERE $__timeFilter\n  and measure_name = '$__measure'\n  and location = 'muenchen-west'\ngroup by bin(time, 1h)\norder by binned_timestamp asc\n"
    },
    {
     "rawQuery": "SELECT \n  bin(time, 1h) as binned_timestamp,\n  avg(measure_value::double) as crowd_lvl\nFROM $__database.$__table\n  WHERE $__timeFilter\n  and measure_name = '$__measure'\n  and location = 'muenchen-ost'\ngroup by bin(time, 1h)\norder by binned_timestamp asc\n"
    },
    {
     "rawQuery": "SELECT \n  bin(time, 1h) as binned_timestamp,\n  avg(measure_value::double) as crowd_lvl\nFROM $__database.$__table\n  WHERE $__timeFilter\n  and measure_name = '$__measure'\n  and location = 'muenchen-einstein'\ngroup by bin(time, 1h)\norder by binned_timestamp asc\n"
    }
   ]
  }
 ]
}